import "./globals.css";
import { Inter } from "next/font/google";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const RootLayout: React.FC<React.PropsWithChildren> = ({ children }) => (
  <html lang="en" className={`${inter.variable} font-sans`}>
    <body>{children}</body>
  </html>
);

export default RootLayout;
